name: Godot testing

on:
  push:
    branches: [ "8-automated-gut-tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: godot -d -s --headless --path . addons/gut/gut_cmdln.gd
