name: Godot testing

on:
  push:
    branches: [ "8-automated-gut-tests" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker test
      uses: ceceppa/godot-gut-ci@main
      with:
        godot_version: 4.1.3 # uses godot 3.2.1
